name: Report
on:
  push:
  schedule:
    - cron: '0 */4 * * *'
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    #env:
      # TZ: Asia/Shanghai
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Report
      run: python main.py ${{ secrets.CLOUDFLARE_ZONE_ID }}  ${{ secrets.CLOUDFLARE_EMAIL }}  ${{ secrets.CLOUDFLARE_API_KEY }}  ${{ secrets.ABUSEIPDB_API_KEY }}
